# -*- coding: utf-8 -*-

"""
/***************************************************************************
ErosionFlow
 A QGIS plugin with QGIS : 32214
 Provides Basic erosion processing algorithms, such as RUSLE AND USPED
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-03-28
        copyright            : (C) 2023 by Michael Tuck
        email                : contact@michaeltuck.com
        MIT LICENCE     
***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Michael Tuck'
__date__ = '2023-03-28'
__copyright__ = '(C) 2023 by Michael Tuck'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ErosionFlow class from file ErosionFlow.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .erosion_flow import ErosionFlowPlugin
    return ErosionFlowPlugin()
